import "./globals.css";
import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from "@clerk/nextjs";
import { dark } from '@clerk/ui/themes';
import { syncUserFromClerk } from "@/actions/user";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const syncedUser = await syncUserFromClerk();
  const dbUser = syncedUser?.success ? syncedUser.user : null;

  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider appearance={{ theme: dark }}>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <Show when="signed-out">
              <SignInButton mode='modal' />
              <SignUpButton mode='modal'>
                <button className="bg-purple-700 text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton>
            </Show>
            <Show when="signed-in">
              {dbUser ? (
                <div className="flex items-center gap-3">
                  <div className="text-sm">
                    <p className="text-gray-400">{dbUser.username}</p>
                    <p className="text-xs font-semibold text-purple-400">{dbUser.role}</p>
                  </div>
                </div>
              ) : null}
              <UserButton />
            </Show>
          </header>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
